Real-World Problem: Analyze Employee Performance Using NumPy
Problem Statement
A company wants to analyze the monthly performance of its employees. The HR department has collected the performance scores of 6 employees for 4 months.
Each employee is evaluated on a scale of 0–100.
Using Python and NumPy, create a program that:
Stores the employee performance data in a NumPy array.
Calculates the average performance score of each employee.
Finds the highest and lowest monthly score for each employee.
Calculates the overall average score of all employees.
Identifies employees whose average score is 80 or above.
Finds which employee has the highest overall performance.
Assigns a performance category:
90+ → Excellent
80–89 → Very Good
70–79 → Good
Below 70 → Needs Improvement

| Employee | Month 1 | Month 2 | Month 3 | Month 4 |
| -------- | ------: | ------: | ------: | ------: |
| Ram      |      85 |      78 |      92 |      88 |
| Sita     |      72 |      80 |      75 |      79 |
| Hari     |      95 |      91 |      89 |      94 |
| Gita     |      65 |      70 |      68 |      72 |
| Krishna  |      88 |      84 |      90 |      86 |
| Mina     |      76 |      82 |      79 |      85 |

In [1]:
import numpy as np 

In [4]:
employees = np.array([
    "Ram", "Sita", "Hari", "Gita", "Krishna", "Mina"
])
print(employees)

['Ram' 'Sita' 'Hari' 'Gita' 'Krishna' 'Mina']


In [5]:
scores = np.array([
    [85, 78, 92, 88],
    [72, 80, 75, 79],
    [95, 91, 89, 94],
    [65, 70, 68, 72],
    [88, 84, 90, 86],
    [76, 82, 79, 85]
])
print(scores)

[[85 78 92 88]
 [72 80 75 79]
 [95 91 89 94]
 [65 70 68 72]
 [88 84 90 86]
 [76 82 79 85]]


In [6]:
average_scores = np.mean(scores, axis=1)
print("Average Scores",average_scores)

Average Scores [85.75 76.5  92.25 68.75 87.   80.5 ]


In [7]:
highest_scores = np.max(scores, axis=1)
print("Higest Scores ",highest_scores)

Higest Scores  [92 80 95 72 90 85]


In [8]:
lowest_scores = np.min(scores, axis=1)
print("Lowest Scores ",lowest_scores)

Lowest Scores  [78 72 89 65 84 76]


In [9]:
overall_average = np.mean(scores)
print("overall Average",round(overall_average,2))

overall Average 81.79


In [10]:
high_performers = employees[average_scores >= 80]

In [11]:
best_index = np.argmax(average_scores)
print("Best Index ",best_index)

Best Index  2


In [12]:
best_employee = employees[best_index]
print("Best employee",best_employee)

Best employee Hari


In [13]:
best_score = average_scores[best_index]
print("best Score",best_score)

best Score 92.25


In [14]:
print("Employee Performance Report")
print("-" * 40)

Employee Performance Report
----------------------------------------


In [16]:
for i in range(len(employees)):
    if average_scores[i] >= 90:
        category = "Excellent"
    elif average_scores[i] >= 80:
        category = "Very Good"
    elif average_scores[i] >= 70:
        category = "Good"
    else:
        category = "Needs Improvement"

    print(
        f"{employees[i]}: "
        f"Average={average_scores[i]:.2f}, "
        f"Highest={highest_scores[i]}, "
        f"Lowest={lowest_scores[i]}, "
        f"Category={category}"
    )


Ram: Average=85.75, Highest=92, Lowest=78, Category=Very Good
Sita: Average=76.50, Highest=80, Lowest=72, Category=Good
Hari: Average=92.25, Highest=95, Lowest=89, Category=Excellent
Gita: Average=68.75, Highest=72, Lowest=65, Category=Needs Improvement
Krishna: Average=87.00, Highest=90, Lowest=84, Category=Very Good
Mina: Average=80.50, Highest=85, Lowest=76, Category=Very Good


In [17]:
print("\nOverall Average:", round(overall_average, 2))



Overall Average: 81.79


In [18]:
print("\nHigh Performers:")
print(high_performers)



High Performers:
['Ram' 'Hari' 'Krishna' 'Mina']


In [19]:
print("\nBest Performer:")
print(best_employee, "-", round(best_score, 2))


Best Performer:
Hari - 92.25
